log file must be declared as output for this to work
if you use the log file of rule A as an input to rule B, then
apparently we need to define it as an output of rule A.... otherwise
snakemake gives us this very clear message:
```
Traceback (most recent call last):
  File
"/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/s
nakemake/__init__.py", line 481, in snakemake
    create_envs_only=create_envs_only)
  File
"/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/s
nakemake/workflow.py", line 364, in execute
    dag.init()
  File
"/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/s
nakemake/dag.py", line 124, in init
    job = self.update([job])
  File
"/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/s
nakemake/dag.py", line 492, in update
    skip_until_dynamic=skip_until_dynamic)
  File
"/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/s
nakemake/dag.py", line 549, in update_
    job.dynamic_input)
  File
"/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/s
nakemake/dag.py", line 492, in update
    skip_until_dynamic=skip_until_dynamic)
  File
"/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/s
nakemake/dag.py", line 549, in update_
    job.dynamic_input)
  File
"/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/s
nakemake/dag.py", line 492, in update
    skip_until_dynamic=skip_until_dynamic)
  File
"/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/s
nakemake/dag.py", line 535, in update_
    job).items()
  File
"/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/s
nakemake/dag.py", line 896, in collect_potential_dependencies
    jobs = [self.new_job(job.dependencies[file], targetfile=file)]
  File
"/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/s
nakemake/dag.py", line 780, in new_job
    wildcards_dict = rule.get_wildcards(targetfile)
  File
"/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/s
nakemake/rules.py", line 695, in get_wildcards
    self.check_wildcards(bestmatch)
  File
"/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/s
nakemake/rules.py", line 425, in check_wildcards
    missing_wildcards = self.wildcard_names - set(wildcards.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```