fixy for the problem Rose Kantor reported on Slack.
Interestingly, Rose was getting this error when running anvi-interactive
or anvi-refine on a profile database that were generated with
--skip-SNV-profiling flag:

Traceback (most recent call last):
File “/home/rkantor/github/anvio/bin/anvi-refine”, line 130, in <module>
d = interactive.Interactive(args)
File “/home/rkantor/github/anvio/anvio/interactive.py”, line 253, in __init__
self.load_full_mode()
File “/home/rkantor/github/anvio/anvio/interactive.py”, line 1282, in load_full_mode
self.load_views(split_names_of_interest=self.split_names_of_interest)
File “/home/rkantor/github/anvio/anvio/dbops.py”, line 3621, in load_views
views_table.pop(‘variability’)
KeyError: ‘variability’

Removing the entire if check here works as well since the view
variability is no longer in the views_table when SNVs_profiled is False,
probably due to changes elsewhere in the codebase, but I'm keeping the
code here in case it may clarify things to some others in the future.